services:
  node:
    build:
      context: .
      dockerfile: lootcoin-node/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - node-data:/app/data
    environment:
      RUST_LOG: info
      PEERS: "https://lootcoin-node.rimba-net.com"
      NODE_URL: "http://node:3000"

  web:
    build:
      context: .
      dockerfile: lootcoin-web/Dockerfile
    ports:
      - "8888:80"

  faucet:
    build:
      context: .
      dockerfile: lootcoin-faucet/Dockerfile
    ports:
      - "3030:3030"
    depends_on:
      - node
    environment:
      RUST_LOG: info
      NODE_URL: "http://node:3000"
      FAUCET_SECRET_KEY: "${FAUCET_SECRET_KEY}"
      DISPENSE_AMOUNT: "500"
      DISPENSE_FEE: "1"
      COOLDOWN_SECS: "86400"

  miner:
    build:
      context: .
      dockerfile: lootcoin-miner/Dockerfile
    depends_on:
      - node
    environment:
      RUST_LOG: info
      NODE_URLS: "http://node:3000"
      MINER_ADDRESS: "${MINER_ADDRESS}"

volumes:
  node-data:
